# Generated by Django 4.0.6 on 2022-07-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_face_recorded',
            field=models.BooleanField(default=False, verbose_name='Is Teacher'),
        ),
    ]
