# Generated by Django 4.0.6 on 2022-07-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0002_user_is_face_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_wajah',
            fields=[
                ('id_wajah', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_file', models.CharField(max_length=1000)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
