# Generated by Django 4.0.5 on 2022-07-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0004_absen_data_absen_remove_jawaban_soal_id_soal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absen',
            old_name='waktu_pengerjaan',
            new_name='jumlah_terisi',
        ),
    ]
