# Generated by Django 4.0.5 on 2022-07-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0005_rename_waktu_pengerjaan_absen_jumlah_terisi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kelas_murid',
            new_name='list_kelas_murid',
        ),
    ]
