# Generated by Django 4.0.5 on 2022-07-07 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0006_rename_kelas_murid_list_kelas_murid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_kelas_murid',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
