# Generated by Django 4.0.5 on 2022-07-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0007_alter_list_kelas_murid_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas_guru',
            name='banner_kelas',
        ),
    ]
